### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by phaberest** [WarWithinMe/better-align#17]
I'm really sorry and honestly am feeling dumb, but I can't get it to work.

Is there any dependency I need to get it to work under OSX?

![Screencast of what it does](http://g.recordit.co/AM0KAassdD.gif)

Using Visual Studio Code 1.17.2 under MacOS X Sierra 10.12.6

**Comment by phaberest** [comment]
Forget it, I was using Operator SSm instead of Operator Mono as font

**Comment by natemccurdy** [comment]
@phaberest Did you get this working? I'm having the same problem, but I don't know what your last comment meant.

**Comment by WarWithinMe** [comment]
@natemccurdy It seems like the Operator Mono is not strictly monospace font (The space seems to be narrower than the other characters). However I'm not sure why the plugin doesn't work for you.

**Comment by christig** [comment]
@phaberest I'm having the same problem and use Operator Mono SSM ...is this font not supported?

edit: nevermind. Operator Mono SSM has nothing to do with my issue. Turns out I had a keybinding conflict. I'm leaving this comment here for anyone that comes along and may find this comment to be of value.
